// S02 reference calculation. Stylized response, not a botanical prediction.
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';

export const CONFIG = Object.freeze({ dt: 0.1, dose: 0.26, evaporation: 0.003,
  rootTau: 6, postureTau: 8, initialMoisture: 0.2, initialPosture: 0.2 });
const clamp = x => Math.max(0, Math.min(1, x));
export function suitability(root) {
  if(root <= 0.25) return 0.2;
  if(root < 0.4) return 0.2 + 0.8 * (root - 0.25) / 0.15;
  if(root <= 0.65) return 1;
  return 1 - 0.85 * (root - 0.65) / 0.35;
}
export function create() {
  return { tick: 0, moisture: CONFIG.initialMoisture, root: CONFIG.initialMoisture,
    posture: CONFIG.initialPosture, watered: 0, runoff: 0, evaporated: 0,
    lastWaterTick: null, events: [] };
}
export function command(s,c) {
  if(!c || typeof c!=='object' || c.type!=='water' || Object.keys(c).some(k=>!['type','tick'].includes(k))) return false;
  const absorbed=Math.min(CONFIG.dose,1-s.moisture);
  const overflow=CONFIG.dose-absorbed;
  s.moisture=clamp(s.moisture+absorbed); s.watered+=CONFIG.dose; s.runoff+=overflow;
  s.lastWaterTick=s.tick;
  if(s.events.length<100) s.events.push({tick:s.tick,type:'water',absorbed,overflow});
  return true;
}
export function step(s) {
  const loss=Math.min(s.moisture,CONFIG.evaporation*CONFIG.dt);
  s.moisture=clamp(s.moisture-loss); s.evaporated+=loss;
  s.root=clamp(s.root+(s.moisture-s.root)*CONFIG.dt/CONFIG.rootTau);
  s.posture=clamp(s.posture+(suitability(s.root)-s.posture)*CONFIG.dt/CONFIG.postureTau);
  s.tick++; check(s);
}
export function check(s) {
  for(const k of ['moisture','root','posture']) assert(Number.isFinite(s[k]) && s[k]>=0 && s[k]<=1);
  assert(Math.abs(CONFIG.initialMoisture+s.watered-s.runoff-s.evaporated-s.moisture)<1e-7);
}
export function projection(s) {
  return { soil: s.moisture<0.3?'dry':s.moisture>0.8?'wet':'moist',
    leaves: s.posture<0.4?'drooping':s.posture<0.7?'lifting':'upright',
    cause: s.root<0.3?'dry-stress':s.root>0.8?'wet-stress':'settling',
    posture:s.posture, moisture:s.moisture };
}
export const CASES = {
  'no-input':[],
  'one-dose':[{tick:50,type:'water'}],
  'repeat-before-response':[{tick:50,type:'water'},{tick:60,type:'water'},{tick:70,type:'water'}],
  'saturated-spam':Array.from({length:30},(_,i)=>({tick:50+i,type:'water'})),
  'spaced-doses':Array.from({length:6},(_,i)=>({tick:50+i*600,type:'water'})),
};
export function run(commands=[],seconds=60) {
  const s=create(), schedule=[...commands].sort((a,b)=>a.tick-b.tick), snapshots=[];
  let i=0, firstLift=null,firstUpright=null;
  for(let tick=0;tick<Math.round(seconds/CONFIG.dt);tick++) {
    while(i<schedule.length && schedule[i].tick===tick)command(s,schedule[i++]);
    step(s);
    if(s.posture>=0.55)firstLift??=s.tick*CONFIG.dt;
    if(s.posture>=0.7)firstUpright??=s.tick*CONFIG.dt;
    if([50,100,150,200,300,600,900,1800,3600].includes(s.tick))snapshots.push({seconds:s.tick*CONFIG.dt,...projection(s)});
  }
  return {s,snapshots,firstLift,firstUpright};
}
if(process.argv[1] && import.meta.url===pathToFileURL(process.argv[1]).href) {
  console.log('# Greenhouse scenario reference traces\n\nGenerated by `node tools/greenhouse-scenario/probe.mjs`. 100 ms ticks, stylized normalized quantities; not browser or botanical evidence.\n');
  console.log('| Case (60 s) | Moisture | Root response | Leaf posture | First posture ≥ 0.55 (s) | First upright ≥ 0.70 (s) | Runoff |');
  console.log('| --- | ---: | ---: | ---: | ---: | ---: | ---: |');
  for(const [name,commands] of Object.entries(CASES)) {
    const {s,firstLift,firstUpright}=run(commands);
    console.log(`| ${name} | ${s.moisture.toFixed(3)} | ${s.root.toFixed(3)} | ${s.posture.toFixed(3)} | ${firstLift?.toFixed(1)??'—'} | ${firstUpright?.toFixed(1)??'—'} | ${s.runoff.toFixed(3)} |`);
  }
  console.log('\n| Case | Time (s) | Moisture | Leaf posture | Soil | Leaf state | Root condition |\n| --- | ---: | ---: | ---: | --- | --- | --- |');
  for(const name of ['no-input','one-dose','repeat-before-response']) for(const x of run(CASES[name]).snapshots)
    console.log(`| ${name} | ${x.seconds} | ${x.moisture.toFixed(3)} | ${x.posture.toFixed(3)} | ${x.soil} | ${x.leaves} | ${x.cause} |`);
  console.log('\n| Longer observation | Time (s) | Moisture | Leaf posture | Root condition |\n| --- | ---: | ---: | ---: | --- |');
  for(const name of ['repeat-before-response','spaced-doses']) for(const x of run(CASES[name],360).snapshots.filter(x=>x.seconds>=60))
    console.log(`| ${name} | ${x.seconds} | ${x.moisture.toFixed(3)} | ${x.posture.toFixed(3)} | ${x.cause} |`);
}
